const libraryBooks = [
  {"id":1,"title":"Anno's Counting Book","author":"Mitsumasa Anno","genre":"Children's","location":"","status":"available","borrower":null,"borrowDate":null},
  {"id":2,"title":"JUDY MOODY","author":"Peter H. Reynolds","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":3,"title":"Judy Moody and the not Bummer Summer","author":"Peter H. Reynolds","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":4,"title":"THE SWORD IN THE STONE","author":"T. H. WHITE","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":5,"title":"JAMES AND THE GIANT PEACH","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":6,"title":"Charlie and the Chocolate Factory","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":7,"title":"BOY TALES OF CHILDHOOD","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":8,"title":"Numberthe Stars","author":"LOIS LOWRY","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":9,"title":"GOING SOLO","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":10,"title":"CHARLIE AND THE GREAT GLASS ELEVATOR","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":11,"title":"Pippi Long stocking","author":"Astrid Lindgren","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":12,"title":"THE 143 -STORY TREE House (camping hoots and soggy boots)","author":"Andy Griffins and Terry Denton","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":13,"title":"CHINESE CINDERELLA","author":"Adeline Yen Mah","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":14,"title":"THE 143 - STORY TREE HOUSE (CAMPING HOOTS AND SOGGY BOOTS)","author":"Andy Griffiths & Terry Denton","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":15,"title":"Madame DOUBTFIRE","author":"Anne Fine","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":16,"title":"HOLES","author":"Louis Sachar","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":17,"title":"Treasure Island","author":"Robert Louis Stevenson","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":18,"title":"ELLA ENCHANTED","author":"Gail Carson Levine","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":19,"title":"CHARLOTTE SOMETIMES","author":"Penelope Farmer","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":20,"title":"CHARLIE AND THE CHOCOLATE FACTORY","author":"ROALD DAHL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":21,"title":"THE COLOUR OF MAGIC","author":"Terry Pratchett","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":22,"title":"DADDY - LONG-LEGS","author":"Jean Webster","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":23,"title":"THE BUTTERFLY LION","author":"Michael Morpugo","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":24,"title":"THE OWL SERVICE","author":"Alan Garner","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":25,"title":"THE SAGA OF ERIK THE VIKING","author":"Terry Jones","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":26,"title":"BLACK BEAUTY","author":"Anna Sewell","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":27,"title":"JUDY MOODY - The Doctor is In","author":"Megan Mcdonald and Peter H. Reynolds","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":28,"title":"MARY POPPINS","author":"P. L. TRAVERS","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":29,"title":"DAISY AND THE TROUBLE WITH SPORTS DAY","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":30,"title":"DAISY AND THE TROUBLE WITH PIGGY BANKS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":31,"title":"DAISY AND THE TROUBLE IN GIANTS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":32,"title":"DAISY AND THE TROUBLE WITH MAGGOTS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":33,"title":"DAISY AND THE TROUBLE WITH VAMPIRES","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":34,"title":"DAISY AND THE TROUBLE WITH BURGLARS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":35,"title":"DAISY AND THE TROUBLE WITH CHRISTMAS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":36,"title":"DAISY AND THE TROUBLE WITH LIFE","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":37,"title":"DAISY AND THE TROUBLE WITH COCONUTS","author":"Kes Gray","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":38,"title":"A LITTLE PRINCESS","author":"Frances Hodgson Burnett","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":39,"title":"HARRY POTTER And the Chamber of Ecrets","author":"J. K. ROWLING","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":40,"title":"SOMEWHERE AROUND THE CORNER","author":"Jackie French","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":41,"title":"CAPTAIN UNDERPANTS And the Invasion of the incredibly Naugthy Cafeteria Ladies","author":"DAV Pilkey","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":42,"title":"CAPTAIN UNDERPANTS AND THE TERRIFYING RE-TURN OF TIPPY TINKLE TROUSERS","author":"DAV Pilkey","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":43,"title":"THE ADVENTURES OF CAPTAIN UNDERPANTS NOW IN FULL COLOR","author":"DAV Pilkey","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":44,"title":"NANCY DREW AND THE CLUE CREW ( Pony Problems)","author":"CAROLYN KEENE/Macky Pamintuan","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":45,"title":"NANCY AND THE CLUE CREW (The Cinderella Ballet Mystery)","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":46,"title":"NANCY AND THE CLUE CREW ( Case of the Sneacky Snowman)","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":47,"title":"NANCY AND THE CLUE CREW (The Fashion Disaster)","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":48,"title":"NANCY DREW AND THE CLUE CREW","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":49,"title":"NANCY DREW AND THE CLUE CREW","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":50,"title":"NANCY DREW AND THE CLUE CREW (The Halloween Hoax)","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":51,"title":"NANCY DREW AND THE CLUE CREW ( Ticket Trouble)","author":"CAROLYN KEENE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":52,"title":"CAPTAIN UNDERPANTS AND THE SENSATIONAL SAGA OF SIR STINKS A-LOT","author":"DAV PILKEY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":53,"title":"CAPTAIN UNDERPANTS AND THE ATTACK OF THE TALKING TOILETS","author":"DAV PILKEY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":54,"title":"THE LEGEND OF THE CAPTAIN CROW'S TEETH","author":"EOIN COLFER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":55,"title":"YOU'RE A BAD MAN, MR. GUM","author":"Andy Stanton","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":56,"title":"CHARLOTTE'S WEB","author":"STUART LITTLE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":57,"title":"HAPPY BIRTHDAY x3","author":"LIBBY GLESSON AND DAVID COX","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":58,"title":"NELSON","author":"TOR FREEMAN AND JUDE FREEMAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":59,"title":"TASHI","author":"ANNA FIENBERG AND BARBARA FIENBERG","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":60,"title":"TASHI AND THE MIXED- UP MONSTER","author":"ANNA FIENBERG AND BARBARA FIENBERG","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":61,"title":"FIRST FAIRY TALES CINDERELLA","author":"MARGARET MAYO *PHILIP NORMAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":62,"title":"WE'RE GOING ON A BEAR HUNT","author":"MICHAEL ROSEN & HELEN OXENBURY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":63,"title":"ARTHUR'S BACK TO SCHOOL DAY","author":"Lilian Hoban","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":64,"title":"TYLER: HIS STORY","author":"RODERICK HUNT","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":65,"title":"THE HUNDRED DRESSES","author":"ELEANOR ESTES","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":66,"title":"PARVANA'S JOURNEY","author":"DEBORAH ELLIS","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":67,"title":"THE SCARECROW AND HIS SERVANT","author":"PHILIP PULLMAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":68,"title":"KING OF THE WIND","author":"MARGUERITE HENRY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":69,"title":"THE EARTH GIANT","author":"MELVIN BURGESS","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":70,"title":"FINDERS KEEPERS","author":"EMILY RODDA","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":71,"title":"THE DAY DREAMER","author":"IAN Mc EWAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":72,"title":"IAM THE CHEESE","author":"ROBERT COMIER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":73,"title":"ELMER'S COLOURS","author":"DAVID MCKEE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":74,"title":"ELMER'S DAY","author":"DAVID MCKEE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":75,"title":"Journey to Jo'burg","author":"Beverly Naidoo","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":76,"title":"Sadako and the THOUSAND PAPER CRANES","author":"ELEANOR COERR","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":77,"title":"The Little Prince","author":"ANTOINE DE SAINT-EXUPERY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":78,"title":"Sarah, Plain and Tall","author":"PATRICIA MACLACHLAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":79,"title":"THE PRINCESS AND THE GOBLIN","author":"George Mcdonald","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":80,"title":"LOVE THAT DOG","author":"SHARON CREECH","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":81,"title":"My SIDE of the MOUNTAIN","author":"JEAN CRAIGHEAD GEOEGE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":82,"title":"MY LIFE WITH THE CHiFANZEES","author":"Jane Goodall","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":83,"title":"Mal Peet keeper","author":"CANEGIE MEDAL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":84,"title":"Ramona and Her Father","author":"Beverly Clearly","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":85,"title":"REDWALL","author":"BRIAN JACQUES","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":86,"title":"THE RED PONY","author":"JOHN STEINBECK","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":87,"title":"THE WIZARD of Oz","author":"L. FRANK BAUM","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":88,"title":"Black Beauty","author":"ANNA SEWELL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":89,"title":"Pippi Longstocking","author":"Astrid Lindgren","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":90,"title":"THE PHANTOM TOLLBOOTH","author":"Norton Juster","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":91,"title":"RAMONA FOREVER","author":"BEVERLY CLEARY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":92,"title":"Charlotte's Web","author":"E. B. WHITE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":93,"title":"ANE OF GREEN GABLES","author":"L. M. Montgomery","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":94,"title":"ALICE'S ADVENTURES IN WONDERLAND AND THROUGH THE LOOKING - GLASS","author":"LEWIS CARROLL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":95,"title":"Lyddie","author":"Katherine Pater","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":96,"title":"MEET JUST WILLIAM AGAIN","author":"Richmal Crompton","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":97,"title":"The Phantom Tollbooth","author":"Norton Juster","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":98,"title":"DICEY'S SONG","author":"CYNTHIA VOIGT","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":99,"title":"THE Railway Children","author":"E. Nesbit","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":100,"title":"The Summer of the Swan","author":"BETSY BYARS","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":101,"title":"Bridge to Terabithia","author":"KATHERINE PATERSON","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":102,"title":"Walk Two Moons","author":"SHARON CREECH","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":103,"title":"Thimble Summer","author":"Elizabeth Enright","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":104,"title":"SOUNDER","author":"William H. Armstrong","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":105,"title":"The Wind in the Willows","author":"KENNETH GRAHAME","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":106,"title":"WHERE THE RED FERN GROWS","author":"Wilson Rawls","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":107,"title":"Island of the Blue Dolphins","author":"SCOTT O'DELL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":108,"title":"The Little House in the Big Woods","author":"LAURA INGALLS WILDER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":109,"title":"The Secret Garden","author":"FRANCES HODGSON BURNETT","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":110,"title":"Skellig","author":"DAVID ALMOND","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":111,"title":"FRAMED the Perfect crime- IT'S A WORK of ART","author":"Frank Cortell- Boyce","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":112,"title":"the CATCHER in the RYE","author":"J. D. SALINGER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":113,"title":"REDWALL","author":"BRIAN JACQUES","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":114,"title":"THE CAY","author":"THEODORE TAYLOR","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":115,"title":"PETER PAN","author":"J. M. BARRIE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":116,"title":"PERCY JACKSON AND THE LIGHTNING THIEF","author":"RICK RIORDAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":117,"title":"GARDEN OF THE PURPLE DRAGON","author":"CAROLE WILKINSON","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":118,"title":"HOW TO TRAIN YOUR DRAGON","author":"CRESSIDA COWELL","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":119,"title":"THE STORY OF Thomas Alva Edison","author":"MARGARET COUSINS","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":120,"title":"AMOS Fortune free man","author":"ELIZABETH YATES","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":121,"title":"CHRONICLES OF ANCIENT DARKNESS - SOUL EATER","author":"MICHELLE PAVER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":122,"title":"CHRONICLES OF ANCIENT DARKNESS - GHOST HUNTER","author":"MICHELLE PAVER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":123,"title":"CHRONICLES OF. ANCIENT DARKNESS - SPIRIT WALKER","author":"MICHELLE PAVER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":124,"title":"CHRONICLES OF ANCIENT DARKNESS - OAT BREAKER","author":"MICHELLE PAVER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":125,"title":"THE TRUMPET Of THE SWAN","author":"E. B. WHITE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":126,"title":"The Family Under the Bridge","author":"NATALIE SAVAGE CARLSON","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":127,"title":"Song of Solomon","author":"Toni Morrison","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":128,"title":"THE FLEDGLING","author":"Jane Langton","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":129,"title":"The Scarecrow and his Servant","author":"PHILIP PULLMAN","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":130,"title":"SWALLOWS AND AMAZONS","author":"ARTHUR RANSOME","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":131,"title":"By the SHORES of SILVER LAKE","author":"LAURA INGALLS WILDER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":132,"title":"DOG MMAN LORD OF THE FLEAS","author":"DAV PILKEY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":133,"title":"ON THE BANKS OF PLUM CREEK","author":"LAURA INGALLS WILDER","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":134,"title":"RUNAWAY RALF","author":"BEVERLY CLEARY","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":135,"title":"A LITTLE PRINCESS","author":"FRANCES HODGSON BURNETT","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":136,"title":"STUART LITTLE","author":"E. B. WHITE","genre":"","location":"AO","status":"available","borrower":null,"borrowDate":null},
  {"id":137,"title":"The BFG","author":"ROALD DAHL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":138,"title":"Stick & FETCH Investigative BARKING UP THE WRONG TREE","author":"Elissa Elwick","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":139,"title":"Shiloh","author":"Phyllis Reynolds Naylor","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":140,"title":"AGENT Amelia Hypno Hounds","author":"MICHAEL BROAD","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":141,"title":"CHRONICLES OF ANCIENT DARKNESS GHOST HUNTER","author":"MICHELLE PAVER","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":142,"title":"KEEPER","author":"Mal peet","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":143,"title":"The Railway Children","author":"E. Nesbit","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":144,"title":"Skellig","author":"DAVID ALMOND","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":145,"title":"My SIDE of the MOUNTAIN","author":"JEAN CRAIGHEAD GEORGE","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":146,"title":"Black Beauty","author":"ANNA SEWEL","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":147,"title":"Chronicles of Ancient Darkness SPIRIT WALKER","author":"MICHELLE PAVER","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":148,"title":"Charlotte's Web","author":"E. B. WHITE","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":149,"title":"THE CHRONICLES OF PRYDAIN","author":"LLOYD ALEXANDER","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":150,"title":"LOVE THAT DOG","author":"SHARON CREECH","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null},
  {"id":151,"title":"Ramona And Her Father","author":"Beverly Clearly","genre":"","location":"T22","status":"available","borrower":null,"borrowDate":null}
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = libraryBooks;
}
